#include <algorithm>
#include <iostream>
#include <iterator>
#include <string>
#include <string_view>
#include <vector>
#include <numeric>
#include <functional>
#include <random>

struct DivisibleBY
{
    const int d;
    //todo to understand these sentence.
    explicit DivisibleBY(int n): d(n) {}
    bool operator()(int n) const {return n % d == 0;}
};
void std_allof_anyof_noneof(){
    /*
     * PREDICATE: describe a callable that returns a value testable as a bool.
     * https://en.cppreference.com/w/cpp/named_req/Predicate
     */
    std::vector<int> v(10,2);
    std::partial_sum(v.cbegin(),v.cend(),v.begin());
    std::cout<<"Amount the numbers: ";
    std::copy(v.cbegin(),v.cend(),std::ostream_iterator<int>(std::cout," "));
    std::cout<<'\n';
    if (std::all_of(v.cbegin(),v.cbegin(),[] (int i) {return i %2==0;}))
        {
        std::cout<<"All numbers are even.";
         }
    if (std::none_of(
            v.cbegin(),
            v.cend(),
            std::bind(std::modulus<>(),std::placeholders::_1,2)))
        {
            std::cout<<"None of them are odd\n";
        }
 }
void std_copy(){
    std::vector<int> from_vector(10);
    std::iota(from_vector.begin(),from_vector.end(),1);
    std::vector<int> to_vector;
    std::copy(from_vector.begin(),from_vector.end(),std::back_inserter(to_vector));
    //or alternatively,
//    std::vector<int> to_vector1(from_vector.size());
//    std::copy(from_vector.begin(),from_vector.end(),to_vector.begin());
    std::cout<<"to vector contains: ";
    std::copy(
            to_vector.begin(),
            to_vector.end(),
            std::ostream_iterator<int>(std::cout," "));
    std::cout<<'\n';
    std::cout<<"Odd numbers in to_vector are: ";
    std::copy_if(
            to_vector.begin(),
            to_vector.end(),
            std::ostream_iterator<int>(std::cout, " "),
            [](int x) {return x %2 !=0;} // lambda by-copy capture by default.
            );
    std::cout<<'\n';
    std::cout<<"to_vector contains these multiples of 3: \n";
    to_vector.clear();
    std::copy_if(
            from_vector.begin(), from_vector.end(),
            std::back_inserter(to_vector),
            [] (int x) {return x % 3 == 0;}
            );
    for (int x:to_vector) std::cout<<x<<' ';
}

void std_findif_find_ifnot(){
    std::vector<int> v{1,3,3,10};
    int  n1 = 3, n2=5;
    auto is_even = [] (int i) {return i%2 == 0;}; //predicate form that can capture something.
    auto result1 = std::find(begin(v),end(v),n1);
    auto result2 = std::find(begin(v),end(v),n2);
    auto result3 = std::find_if(begin(v), end(v),is_even);
    (result1 != std::end(v))
        ? std::cout<<"V contains " <<n1<<'\n'
        : std::cout<<"V does not contain "<<n1<<'\n';

    (result2 != std::end(v))
        ? std::cout<<"V contains "<<n2<<'\n'
        : std::cout<<"V does not contains "<<n2<<'\n';

    (result3 != std::end(v))
        ? std::cout<< "V contains even number: "<<*result3<<'\n'
        : std::cout<< "V does not contain even numbers\n";
    if(result3 !=  std::end(v))
        std::cout<<"result3 deference "<<*result3<<" endl.";
}

void std_generate_n()
{
    std::mt19937 rng;
    std::generate_n(
            std::ostream_iterator<std::mt19937::result_type>(std::cout, " "),
                    5,
                    std::ref(rng)
            );
   std::cout<<'\n';
}
void std_mt19937_demo()
{
    // pseudo-random number generator.
    std::mt19937 mt;
    mt.seed(1289); //reinitializes the seed value of object.
    std::cout<<"random numbers generated by mt19937 are: \n";
    for (int i=5; i>0;i--) std::cout<<mt()<<' ';
}

using container = std::vector<std::string>;
void print(std::string_view comment, const container& src, const container& dst = {})
{
    auto prn = [](std::string_view name, const container& cont) {
        std::cout << name;
        for (const auto &s: cont) { std::cout << (s.empty() ? "." : s.data()) << ' '; }
        std::cout << '\n';
    };
    std::cout << comment << '\n';
    prn("src: ", src);
    if (dst.empty()) return;
    prn("dst: ", dst);
}



int main() {
    std::cout<<"line begin;\n";

    container src{"foo","bar","baz"};
    container dst{"qux","quxx","quuz","corge"};
    print("Non-overlapping case: before move_backward: ",src,dst);
    /* Moves the elements from the range [first, last), to another range ending at d_last.
     * The last element move first, but their relative order is preserved.
     */
    std::move_backward(src.begin(),src.end(), dst.end());
    print("After: ",src,dst);
    src = {"snap","crackle","pop","lock","drop"};

    std::move_backward(src.begin(),src.begin()+3,src.end());
    std::cout<<src.size(); //move only make content null, does not reduce size.

    //    std::vector<int> v{1,5,8};
//    std_allof_anyof_noneof();
//    std_copy(); //https://en.cppreference.com/w/cpp/algorithm/copy

// any_of demo.
//    if(std::any_of(v.cbegin(),v.cend(), DivisibleBY(7)))
//        std::cout<<"At least one number is divisible by 7.\n";
//    else std::cout<<"No number is divisible by 7.\n";

/* std::find, std::find_if, std::find_if_not.
 * https://en.cppreference.com/w/cpp/algorithm/find
 * */
    //todo find if, two case, return one element or return more than one element.
//    std_findif_find_ifnot();

//        std_mt19937_demo(); // https://www.geeksforgeeks.org/stdmt19937-class-in-cpp/

    std::cout<<"\t---line ends;\n";return 0;


}
